# Generated by Django 2.1.5 on 2020-05-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
