# Generated by Django 2.1.5 on 2020-05-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20200524_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(max_length=500),
        ),
    ]
